from typing import List


def msg_to_midi(msg: str) -> List[int]:
    """Converts messages from the client to midi message in pygame.midi.Input format.

    Parameters
    ----------
    msg : str
        format is b"TTTNNNVVVSSSS"

    Returns
    -------
    List:
        [[type, note, velocity], timestamp]
    """
    msg_list = str(msg).split(",")
    type, note, velocity, timestamp = msg_list
    type = type[2:]
    timestamp = int(timestamp[:-1])
    midi = [int(type), int(note), int(velocity)]
    return [midi, timestamp]


def midi_to_msg(msg: List[int]) -> str:
    """Converts a midi input List generated by pygame.midi.Input(device).read(1)[0] to string.

    Parameters
    ----------
    msg : List[int]
        [[type, note, velocity],timestamp]

    Returns
    -------
    str
        delimtered string of format:
        b"type,note,velocity,timestamp"
    """
    data = msg[0]
    time = msg[1]
    msg_str = ",".join([str(e) for e in data])
    msg_str += "," + str(time)
    return msg_str
